### ISSUE TITLE
Rescale PSF with respect to Z step

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/stitching-spark#17]
Samples are typically imaged with 180nm Z step, while PSFs are usually acquired using 100nm step to improve accuracy. Need to rescale the PSF before running deconvolution with respect to the ratio between the pixel resolutions in Z.

**Comment by CharlesHan95** [comment]
have you done the rescale of the psf, i followed the paper<Extended depth-resolved imaging through a thin scattering medium with PSF manipulation>,but i failed to rescale the psf,maybe my method was wrong, if you are doing the same job, please email me about what you thought(charleshan95@gmail.com)

**Comment by CharlesHan95** [comment]
have you done the rescale of the psf, i followed the paper'Extended depth-resolved imaging through a thin scattering medium with PSF manipulation',but i failed to rescale the psf,maybe my method was wrong, if you are doing the same job, please email me about what you thought(charleshan95@gmail.com)
